apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
  - host: archerfrank.com
    http:
      paths:
      - path: /
        backend:
          serviceName: customer-service
          servicePort: 8092